### PR TITLE
create proposal.md

### PR DESCRIPTION
**Pull request by ct-clmsn**
provide a skeleton in markdown. suggest using markdown for start of project. move to latex later?

### CODE REVIEW

**Comment by shefty** [comment]
I'm good with markdown.

The DCO is wanting a signed-off-by line as part of the commit.  Note that this repo is not associated with any license.  I'm not sure that anything makes sense for that.  I'll see if we can disable DCO for this repo.

Based on email responses from the cpp community, we may need to create a working implementation of ASIO.  That could mean providing a fork of the asio code into the ofiwg.

**Comment by shefty** [comment]
Reading the DCO, I think we want to keep it.  Although it's mainly for code, I guess we need to verify that any text that is submitted must be approved to help guard against copyright infringement.

**Comment by ct-clmsn** [comment]
> The DCO is wanting a signed-off-by line as part of the commit. Note that this repo is not associated 
> with any license. I'm not sure that anything makes sense for that. I'll see if we can disable DCO for this 
> repo.

I'll have to read up on how that works. I'm a novice with the DCO functionality.

> Based on email responses from the cpp community, we may need to create a working implementation 
> of ASIO. That could mean providing a fork of the asio code into the ofiwg.
>
> Reading the DCO, I think we want to keep it. Although it's mainly for code, I guess we need to verify
> that any text that is submitted must be approved to help guard against copyright infringement.
>

Understood!

**Comment by ct-clmsn** [comment]
@shefty - my struggle with DCO is almost complete.

**Comment by jsquyres** [comment]
I think your last commit was good -- it had the right signoff.  But the DCO failed it because it has to fail the last commit to make the overall test fail (since the other commits are not good).

You might want to:

* Squash down to 1 commit
* Change the commit author to `Chris Taylor <ct.clmsn@gmail.com>`
* Change your signoff line to also be `Chris Taylor <ct.clmsn@gmail.com>`

**Comment by shefty** [comment]
:)  You're adding new commits.  You need to squash all the commits into one, with the commit message containing the Signed-off-by: line.

**Comment by ct-clmsn** [comment]
@jsquyres @shefty got it. i'm stuck using the github browser interface at the moment. DCO is returning this error message: ` Expected "ct-clmsn <ct.clmsn@gmail.com>", but got "ct.clmsn <ct.clmsn@... `

**Comment by shefty** [comment]
I merged these manually through my tree -- squashing all commits into one, which fixes the DCO issue.  See PR #2

**Pull request closed without merging**
